---
  - hosts: all
    sudo: true
    tasks:
      - name: Crear directorio para almacenar web
        file: path=www state=directory

      - name: Actualizar cache para distros tipo Debian
        apt: update_cache=yes
        when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

      - name: Actualizar cache para distros tipo CentOS
        yum: update_cache=yes
        when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

      - name: instalar Numpy
        package:
          name: python-numpy
          state: present

      - name: instalar Git
        package:
          name: git
          state: present

      - name: descargar repositorio app
        shell: git clone https://github.com/Griger/aplicacionPruebaCC.git
        args:
          chdir: ~
          creates: aplicacionPruebaCC

      - name: ejecutar aplicacion
        shell: python app.py
        register: output
        args:
          chdir: aplicacionPruebaCC

      - debug:
          var: output.stdout_lines
